site_name: DocuAndre
site_url: https://mydomain.org/mysite
theme:
  name: material
  logo: docs/logo.svg
  palette:

    # light mode
    - scheme: settlenext
    
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
  - navigation.instant 
  - navigation.instant.progress
  - navigation.instant.preview
  - navigation.tracking
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.expand
  - navigation.indexes
  - toc.integrate
  - navigation.top
  - search.suggest
  - search.highlight
  - content.code.copy

plugins:
  - search
  - tags:
      tags_file: tags.md
  - blog 

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Documentazione:
    - Java: documentazione/primaprova.md
  - Biografia: 
    - Chi Sono: about/about.md
    - Cosa Faccio: about/cosafaccio.md
  - Tags: tags.md
  - Blog:
    - Archivio: blog/index.md